bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost user=pathfinder password=password dbname=library sslmode=disable"
database_url_mysql = "root:password@tcp(127.0.0.1)/library?charset=utf8"